### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by sabahatatta**
Please merge this updated list. Sorry for the inconvenience caused due to multiple PR as I ran to some issue while updating the list.

### CODE REVIEW

**Review by davidetaibi — CHANGES_REQUESTED** [review]
Could you help me to fix the conflicts?

**Comment by sabahatatta** [comment]
> Could you help me to fix the conflicts?

Yes sure

**Review by sabahatatta — COMMENTED** [review]
Hey Davide,

You have the write access and only you can resolve the conflicts. If you need help any other regard you are more than welcome.

**Comment by davidetaibi** [comment]
> Hey Davide,
> 
> You have the write access and only you can resolve the conflicts. If you need help any other regard you are more than welcome.

I added you as a collaborator. Please accept the invitation, so as to accept the PR and merge the conflicts by yourself ;-)

**Comment by davidetaibi** [comment]
Unfortunately you have overwritten the previous changes

The table had a slightly different structure, links were reported as links not with the complete url and there were also other information on the number of microservices and the patterns used in some projects...

Could you please revert to the previous commit and manually merge the conflicts?

**Comment by davidetaibi** [comment]
We manually fixed the issue. No need to take actions anymore ;-)

**Pull request merged**
